import {FC} from 'react'
import Head from 'next/head'

export const CustomHead: FC = ()=>{
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
